<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Philippe Marchand, Université du Québec en Abitibi-Témiscamingue" />

<meta name="date" content="2020-05-07" />

<title>Introduction to geospatial data analysis in R</title>

<script src="libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="libs/bootstrap-3.3.5/css/united.min.css" rel="stylesheet" />
<script src="libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="libs/navigation-1.1/tabsets.js"></script>
<link href="libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>





<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>



<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Introduction to geospatial data analysis in R</h1>
<h4 class="author">Philippe Marchand, Université du Québec en Abitibi-Témiscamingue</h4>
<h4 class="date">May 7, 2020</h4>

</div>


<hr />
<p>This workshop provides an overview of tools available in R for the analysis of geolocated data. This type of data is becoming increasingly common in various fields (e.g. aerial photos, satellite imagery, census data, geolocated posts on social networks, etc.). There are two broad categories of geospatial data:</p>
<ul>
<li>raster data represent variables defined at every point of a grid covering the full extent of the data (as in satellite images);</li>
<li>vector data associate variables (sometimes also called attributes) to discrete geometrical objects located in space (such as the position of cities and highways on a road map).</li>
</ul>
<p>At first, using programming commands to process geographical data can seem less intuitive, compared with the graphical user interface of GIS software. Here are a few advantages of scripted analyses:</p>
<ul>
<li>It is easy to repeat the analysis for new data by re-running the script.</li>
<li>It is easy for other researchers to reproduce the methods if they have access to the same programming language.</li>
<li>When using R specifically, the spatial data can be extracted and merged with other datasets for statistical analyses in a single programming environment.</li>
</ul>
<div id="objectives" class="section level2">
<h2>Objectives</h2>
<ul>
<li>Become familiar with R packages for processing and simple visualization of vector and raster data (the <strong><em>sf</em></strong> and <strong><em>stars</em></strong> packages, respectively).</li>
<li>Perform common data transformation operations using functions from those packages.</li>
<li>Create more complex static maps (with <strong><em>ggplot2</em></strong>) and interactive maps (with <strong><em>mapview</em></strong>).</li>
</ul>
<div id="note-on-packages" class="section level3">
<h3>Note on packages</h3>
<ul>
<li><p>The set of packages available for spatial analysis in R has evolved rapidly. A few years ago, the <strong><em>sp</em></strong> and <strong><em>raster</em></strong> packages were the main tools for vector and raster data processing, respectively. <strong><em>sf</em></strong> and <strong><em>stars</em></strong> are part of a recent initiative to overhaul R spatial tools (<a href="https://www.r-spatial.org/">https://www.r-spatial.org/</a>).</p></li>
<li><p>The <strong><em>sf</em></strong> package represents spatial data frames with a standard format based on open-source geodatabases, and integrates well with popular R packages for data manipulation and visualization (such as <strong><em>dplyr</em></strong> and <strong><em>ggplot2</em></strong>).</p></li>
<li><p>The <strong><em>stars</em></strong> package is also compatible with <strong><em>ggplot2</em></strong> and provides good support for raster “cubes” with non-spatial dimensions such as time.</p></li>
<li><p>The <strong><em>raster</em></strong> package and its successor <strong><em>terra</em></strong> (released in 2020) have some features not present in <strong><em>stars</em></strong> and perform some operations faster. Therefore it can be useful to learn them if your workflow includes complex operations on large rasters; see the documentation at <a href="https://rspatial.org/">https://rspatial.org/</a> for more details.</p></li>
</ul>
</div>
</div>
<div id="contents" class="section level2">
<h2>Contents</h2>
<ul>
<li><a href="#vect">Explore a vector dataset</a></li>
<li><a href="#crs">Coordinate reference systems and transformations</a></li>
<li><a href="#geomsf">Customize maps with ggplot2</a></li>
<li><a href="#vectop">Geometric operations on vector data</a></li>
<li><a href="#rast">Raster datasets</a></li>
<li><a href="#mapview">Interactive maps with <em>mapview</em></a></li>
<li><a href="#ref">Additional references</a></li>
<li><a href="#data">Data sources</a></li>
<li><a href="#sol">Exercise solutions</a></li>
</ul>
<hr />
</div>
<div id="vect" class="section level2">
<h2>Explore a vector dataset</h2>
<p>All datasets used in this workshop can be found in the <em>data</em> folder. The <em>mrc</em> dataset contains information on Québec regional county municipalities (MRCs) in a <em>ESRI shapefile</em> format. Note that a single shapefile dataset is spread across multiple files, which share a name but differ in their file extension (<em>mrc.dbf</em>, <em>mrc.prj</em>, <em>mrc.shp</em> and <em>mrc.shx</em>).</p>
<p>To load this dataset in R, we call the <code>st_read</code> function from <strong><em>sf</em></strong> (all <strong><em>sf</em></strong> package functions start with the prefix <code>st_</code>, standing for spatiotemporal) and provide the path to the <em>.shp</em> file.</p>
<pre class="r"><code>library(sf)

mrc &lt;- st_read(&quot;data/mrc.shp&quot;)</code></pre>
<pre><code>## Reading layer `mrc&#39; from data source `/research-home/rblake/atelier_rgeo/data/mrc.shp&#39; using driver `ESRI Shapefile&#39;
## Simple feature collection with 104 features and 4 fields
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: -79.7625 ymin: 44.99136 xmax: -56.93495 ymax: 62.58217
## CRS:           4269</code></pre>
<p>The output text indicates the main properties of the loaded dataset, including the geometric type (MULTIPOLYGON), the spatial extent of the data (<em>bbox</em>) and the coordinate reference system (CRS) in use.</p>
<p>The bounding box and a detailed description of the CRS can be accessed separately using the <code>st_bbox</code> and <code>st_crs</code> functions:</p>
<pre class="r"><code>st_bbox(mrc)</code></pre>
<pre><code>##      xmin      ymin      xmax      ymax 
## -79.76250  44.99136 -56.93495  62.58217</code></pre>
<pre class="r"><code>st_crs(mrc)</code></pre>
<pre><code>## Coordinate Reference System:
##   User input: 4269 
##   wkt:
## GEOGCS[&quot;GCS_North_American_1983&quot;,
##     DATUM[&quot;North_American_Datum_1983&quot;,
##         SPHEROID[&quot;GRS_1980&quot;,6378137,298.257222101]],
##     PRIMEM[&quot;Greenwich&quot;,0],
##     UNIT[&quot;Degree&quot;,0.017453292519943295],
##     AUTHORITY[&quot;EPSG&quot;,&quot;4269&quot;]]</code></pre>
<p>We will discuss coordinate systems in the next section. For now, note that “Degree” under <code>UNIT</code> specifies that these are longitude and latitude coordinates expressed in decimal degrees.</p>
<p>Let us look at the first few rows of the data:</p>
<pre class="r"><code>class(mrc)</code></pre>
<pre><code>## [1] &quot;sf&quot;         &quot;data.frame&quot;</code></pre>
<pre class="r"><code>head(mrc)</code></pre>
<pre><code>## Simple feature collection with 6 features and 4 fields
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: -79.51776 ymin: 45.44911 xmax: -63.31941 ymax: 62.58217
## CRS:           4269
##                           mrc_name reg_id              reg_name pop2016
## 1                          Abitibi     08 Abitibi-Temiscamingue   24707
## 2                    Abitibi-Ouest     08 Abitibi-Temiscamingue   20582
## 3                            Acton     16            Monteregie   15623
## 4 Administration regionale Kativik     10        Nord-du-Quebec   13343
## 5                  Antoine-Labelle     15           Laurentides   35410
## 6                       Argenteuil     15           Laurentides   32477
##                         geometry
## 1 MULTIPOLYGON (((-78.64359 4...
## 2 MULTIPOLYGON (((-79.51776 4...
## 3 MULTIPOLYGON (((-72.70415 4...
## 4 MULTIPOLYGON (((-77.82293 5...
## 5 MULTIPOLYGON (((-75.52133 4...
## 6 MULTIPOLYGON (((-74.71004 4...</code></pre>
<p>An <code>sf</code> object is a specialized <code>data.frame</code> where each line contains data associated with a geometry element (or <em>simple feature</em>, hence the package name), which is described in the <code>geometry</code> column. The most common feature types are:</p>
<ul>
<li>POINT: Coordinates (<em>x</em>, <em>y</em>) of a point.</li>
<li>LINESTRING: Sequence of points connected by length segments.</li>
<li>POLYGON: Sequence of points creating a closed simple polygon.</li>
<li>MULTIPOINT, MULTILINESTRING ou MULTIPOLYGON: Dataset where each feature can be composed of multiple points, linestrings or polygons.</li>
</ul>
<p>The <code>plot</code> function applied to an <code>sf</code> object creates a map for each field in the dataset.</p>
<pre class="r"><code>plot(mrc)</code></pre>
<p><img src="rgeo_workshop_files/figure-html/plot_sf-1.png" width="672" /></p>
<p>To plot a single variable, you need to select the corresponding column. To show a map without data variables, you can select the <em>geometry</em> column. The <code>axes = TRUE</code> parameter tells R to show coordinate axes.</p>
<pre class="r"><code>plot(mrc[&quot;geometry&quot;], axes = TRUE)</code></pre>
<p><img src="rgeo_workshop_files/figure-html/plot_geom-1.png" width="672" /></p>
<p>You can select a subset of rows or columns of an <code>sf</code> object just like a regular data frame.</p>
<pre class="r"><code># Select the 5th row
mrc[5, ]</code></pre>
<pre><code>## Simple feature collection with 1 feature and 4 fields
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: -76.14932 ymin: 45.95376 xmax: -74.34359 ymax: 47.76333
## CRS:           4269
##          mrc_name reg_id    reg_name pop2016                       geometry
## 5 Antoine-Labelle     15 Laurentides   35410 MULTIPOLYGON (((-75.52133 4...</code></pre>
<pre class="r"><code># Select the MRC name and population columns for MRCs with a population over 200,000
mrc[mrc$pop2016 &gt; 200000, c(&quot;mrc_name&quot;, &quot;pop2016&quot;)] </code></pre>
<pre><code>## Simple feature collection with 5 features and 2 fields
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: -75.90834 ymin: 45.37075 xmax: -71.13162 ymax: 46.98186
## CRS:           4269
##     mrc_name pop2016                       geometry
## 23  Gatineau  278198 MULTIPOLYGON (((-75.89532 4...
## 47     Laval  425225 MULTIPOLYGON (((-73.74488 4...
## 69 Longueuil  417497 MULTIPOLYGON (((-73.44474 4...
## 82  Montreal 1959836 MULTIPOLYGON (((-73.49801 4...
## 89    Quebec  572755 MULTIPOLYGON (((-71.55293 4...</code></pre>
<p>Note that the column containing the spatial information (<em>geometry</em>) is always retained, even if not explicitly selected. To discard that column and convert the <code>sf</code> object to a regular (non-spatial) data frame, you can use the function <code>st_drop_geometry</code>.</p>
<div id="retour1" class="section level3">
<h3>Exercise 1</h3>
<p>Select the MRCs in the Bas-St-Laurent (<em>reg_id</em>: 01) and Gaspesie (<em>reg_id</em>: 11) regions, then display their 2016 population on a map.<br />
<em>Hint</em>: The operator <code>%in%</code> can check if a variable has one value within a set, for example <code>x %in% c(1, 3)</code> returns TRUE if <em>x</em> is equal to 1 or 3.</p>
<p><a href="#sol1">Solution</a></p>
</div>
<div id="integration-with-the-dplyr-package" class="section level3">
<h3>Integration with the dplyr package</h3>
<p>The data manipulation functions from the <strong><em>dplyr</em></strong> package work on <code>sf</code> objects as well. For example, we could rewrite the example above (select the name and population of MRCs with populations over 200,000) using <code>filter</code> and <code>select</code>.</p>
<pre class="r"><code>library(dplyr)

filter(mrc, pop2016 &gt; 200000) %&gt;%
    select(mrc_name, pop2016)</code></pre>
<pre><code>## Simple feature collection with 5 features and 2 fields
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: -75.90834 ymin: 45.37075 xmax: -71.13162 ymax: 46.98186
## CRS:           4269
##    mrc_name pop2016                       geometry
## 1  Gatineau  278198 MULTIPOLYGON (((-75.89532 4...
## 2     Laval  425225 MULTIPOLYGON (((-73.74488 4...
## 3 Longueuil  417497 MULTIPOLYGON (((-73.44474 4...
## 4  Montreal 1959836 MULTIPOLYGON (((-73.49801 4...
## 5    Quebec  572755 MULTIPOLYGON (((-71.55293 4...</code></pre>
<p>When performing a grouped summary, the individual features are also aggregated in a single feature by group. For example, let us aggregate the MRCs and their population by region.</p>
<pre class="r"><code>regions &lt;- group_by(mrc, reg_name) %&gt;%
    summarize(pop2016 = sum(pop2016))</code></pre>
<pre><code>## although coordinates are longitude/latitude, st_union assumes that they are planar
## although coordinates are longitude/latitude, st_union assumes that they are planar
## although coordinates are longitude/latitude, st_union assumes that they are planar
## although coordinates are longitude/latitude, st_union assumes that they are planar
## although coordinates are longitude/latitude, st_union assumes that they are planar
## although coordinates are longitude/latitude, st_union assumes that they are planar
## although coordinates are longitude/latitude, st_union assumes that they are planar
## although coordinates are longitude/latitude, st_union assumes that they are planar
## although coordinates are longitude/latitude, st_union assumes that they are planar
## although coordinates are longitude/latitude, st_union assumes that they are planar
## although coordinates are longitude/latitude, st_union assumes that they are planar
## although coordinates are longitude/latitude, st_union assumes that they are planar
## although coordinates are longitude/latitude, st_union assumes that they are planar
## although coordinates are longitude/latitude, st_union assumes that they are planar
## although coordinates are longitude/latitude, st_union assumes that they are planar
## although coordinates are longitude/latitude, st_union assumes that they are planar
## although coordinates are longitude/latitude, st_union assumes that they are planar</code></pre>
<pre class="r"><code>head(regions)</code></pre>
<pre><code>## Simple feature collection with 6 features and 2 fields
## Geometry type: GEOMETRY
## Dimension:     XY
## Bounding box:  xmin: -79.57933 ymin: 45.58943 xmax: -56.93495 ymax: 55.00006
## CRS:           4269
## # A tibble: 6 x 3
##   reg_name         pop2016                                              geometry
##   &lt;chr&gt;              &lt;dbl&gt;                                        &lt;GEOMETRY [°]&gt;
## 1 Abitibi-Temisca…  147282 POLYGON ((-77.93147 47.27012, -77.93155 47.26624, -7…
## 2 Bas-Saint-Laure…  197806 POLYGON ((-68.38319 47.88014, -68.38314 47.83307, -6…
## 3 Capitale-Nation…  733898 POLYGON ((-70.69151 47.03311, -70.69453 47.02324, -7…
## 4 Centre-du-Quebec  243354 POLYGON ((-72.09283 45.79699, -72.11938 45.77338, -7…
## 5 Chaudiere-Appal…  421993 POLYGON ((-70.2784 46.05675, -70.2784 46.05608, -70.…
## 6 Cote-Nord          92712 MULTIPOLYGON (((-66.25978 55.00001, -66.25001 55, -6…</code></pre>
<pre class="r"><code>plot(regions[&quot;pop2016&quot;])</code></pre>
<p><img src="rgeo_workshop_files/figure-html/sf_groupby-1.png" width="672" /></p>
</div>
<div id="create-a-spatial-object-from-a-data-frame" class="section level3">
<h3>Create a spatial object from a data frame</h3>
<p>The <code>plots_rgeo.csv</code> file contains data from forest inventory plots of the Québec Department of Forests, Wildlife and Parks (MFFP), including the plot ID, latitude and longitude, survey date, cover type (deciduous, mixed or coniferous) and canopy height class.</p>
<pre class="r"><code>plots &lt;- read.csv(&quot;data/plots_rgeo.csv&quot;)
head(plots)</code></pre>
<pre><code>##    plot_id      lat      long  surv_date cover_type height_cls
## 1 99100101 45.35944 -72.89580 2012-11-12  Deciduous    17-22 m
## 2 99100102 45.36267 -72.89244 2012-09-08  Deciduous      &gt;22 m
## 3 99100201 45.49196 -71.16727 2008-09-11  Deciduous    17-22 m
## 4 99100202 45.49068 -71.16180 2008-09-11  Deciduous    17-22 m
## 5 99100301 45.47711 -72.58792 2012-08-30  Deciduous      &gt;22 m
## 6 99100302 45.47969 -72.58448 2012-08-30  Deciduous      &gt;22 m</code></pre>
<p>We can convert this data to an <code>sf</code> object with <code>st_as_sf</code>. The <code>coords</code> argument specifies which columns hold the X and Y coordinates, while the <code>crs</code> argument defines the coordinate reference system (here, it is set to the same CRS as the MRC dataset).</p>
<pre class="r"><code>plots &lt;- st_as_sf(plots, coords = c(&quot;long&quot;, &quot;lat&quot;), crs = st_crs(mrc))
plot(plots[&quot;geometry&quot;])</code></pre>
<p><img src="rgeo_workshop_files/figure-html/df_to_sf-1.png" width="672" /></p>
</div>
<div id="review" class="section level3">
<h3>Review</h3>
<ul>
<li>Spatial vector data associate data fields to localized geometric features such as points, lines and polygons. The <strong><em>sf</em></strong> package can be used to work with those datasets in R.</li>
<li>To read a vector dataset: <code>st_read</code>.</li>
<li>To convert a regular <code>data.frame</code> into a spatial object: <code>st_as_sf</code>.</li>
<li>All basic <code>data.frame</code> operations, as well as <strong><em>dplyr</em></strong> package operations, also apply to <code>sf</code> objects.</li>
<li>The <code>plot</code> function applied to an <code>sf</code> object displays one or many data fields on a map.</li>
</ul>
<hr />
</div>
</div>
<div id="crs" class="section level2">
<h2>Coordinate reference systems and transformations</h2>
<p>Until now, we worked with data using a geographic coordinate system, with positions described as degrees of longitude and latitude. Those coordinates are based on a model that approximates the irregular surface of the Earth’s mean sea level (the geoid) as an ellipsoid (a slightly flattened sphere). That model is specified as a <em>datum</em> in the CRS description. The <code>mrc</code> shapefile uses the NAD83 (North American) datum, whereas many world maps are based on the WGS84 datum.</p>
<pre class="r"><code>st_crs(mrc)</code></pre>
<pre><code>## Coordinate Reference System:
##   User input: 4269 
##   wkt:
## GEOGCS[&quot;GCS_North_American_1983&quot;,
##     DATUM[&quot;North_American_Datum_1983&quot;,
##         SPHEROID[&quot;GRS_1980&quot;,6378137,298.257222101]],
##     PRIMEM[&quot;Greenwich&quot;,0],
##     UNIT[&quot;Degree&quot;,0.017453292519943295],
##     AUTHORITY[&quot;EPSG&quot;,&quot;4269&quot;]]</code></pre>
<p>A projection converts geographical coordinates in cartesian or rectangular (X, Y) coordinates. Since it is impossible to provide an exact representation of a curved surface on a plane, specialized projections were developed for different regions of the world and different analytical applications.</p>
<p>For example, the images below show how identical circular areas appear at different points of the Earth under a Mercator projection (which preserves shapes) and a Lambert equal-area projection (which preserves areas).</p>
<p><img src="images/Mercator_distortion.png" alt="Mercator projection" /> <img src="images/Lambert_distortion.png" alt="Lambert equal-area projection" /></p>
<p>We will convert the <code>mrc</code> polygons into a Lambert conical conformal projection centered on Quebec (<a href="https://epsg.io/6622">EPSG:6622</a>), using <code>st_transform</code>.</p>
<pre class="r"><code>mrc_proj &lt;- st_transform(mrc, crs = 6622)
st_crs(mrc_proj)</code></pre>
<pre><code>## Coordinate Reference System:
##   User input: EPSG:6622 
##   wkt:
## PROJCS[&quot;NAD83(CSRS) / Quebec Lambert&quot;,
##     GEOGCS[&quot;NAD83(CSRS)&quot;,
##         DATUM[&quot;NAD83_Canadian_Spatial_Reference_System&quot;,
##             SPHEROID[&quot;GRS 1980&quot;,6378137,298.257222101,
##                 AUTHORITY[&quot;EPSG&quot;,&quot;7019&quot;]],
##             TOWGS84[0,0,0,0,0,0,0],
##             AUTHORITY[&quot;EPSG&quot;,&quot;6140&quot;]],
##         PRIMEM[&quot;Greenwich&quot;,0,
##             AUTHORITY[&quot;EPSG&quot;,&quot;8901&quot;]],
##         UNIT[&quot;degree&quot;,0.0174532925199433,
##             AUTHORITY[&quot;EPSG&quot;,&quot;9122&quot;]],
##         AUTHORITY[&quot;EPSG&quot;,&quot;4617&quot;]],
##     PROJECTION[&quot;Lambert_Conformal_Conic_2SP&quot;],
##     PARAMETER[&quot;standard_parallel_1&quot;,60],
##     PARAMETER[&quot;standard_parallel_2&quot;,46],
##     PARAMETER[&quot;latitude_of_origin&quot;,44],
##     PARAMETER[&quot;central_meridian&quot;,-68.5],
##     PARAMETER[&quot;false_easting&quot;,0],
##     PARAMETER[&quot;false_northing&quot;,0],
##     UNIT[&quot;metre&quot;,1,
##         AUTHORITY[&quot;EPSG&quot;,&quot;9001&quot;]],
##     AXIS[&quot;X&quot;,EAST],
##     AXIS[&quot;Y&quot;,NORTH],
##     AUTHORITY[&quot;EPSG&quot;,&quot;6622&quot;]]</code></pre>
<p>EPSG codes are useful to quickly specify a projection. The detailed description includes the type of projection (Lambert conformal conic), additional parameters of the projection, as well as the units (metres) for the projected data. The coordinates in metres are relative to a point of origin specified in the projection parameters (<em>latitude_of_origin</em> and <em>central_meridian</em>).</p>
<pre class="r"><code>plot(mrc_proj[&quot;geometry&quot;], axes = TRUE)</code></pre>
<p><img src="rgeo_workshop_files/figure-html/plot_geom_proj-1.png" width="672" /></p>
<p>To create a map with latitude and longitude lines superposed on projected data, we can specify a geographical coordinate system (here, based on the original data) to the <code>graticule</code> argument:</p>
<pre class="r"><code>plot(mrc_proj[&quot;geometry&quot;], axes = TRUE, graticule = st_crs(mrc))</code></pre>
<p><img src="rgeo_workshop_files/figure-html/plot_graticule-1.png" width="672" /></p>
<p>It is important to always use <code>st_transform</code> to convert datasets between different coordinate systems. A common error consists in modifying the coordinate system of a dataset (for example, with <code>st_crs</code>) without transforming the data themselves.</p>
<div id="review-1" class="section level3">
<h3>Review</h3>
<ul>
<li>Geographic coordinate systems are based on a <em>datum</em> (model of the Earth’s shape) and describe the position in terms of spherical coordinates (longitude, latitude) measured in degrees.</li>
<li>Projected coordinate systems convert spherical coordinates into rectangular coordinates (<em>x</em>, <em>y</em>) measured in a unit of length such as metres.</li>
<li><code>st_crs</code> returns the coordinate system of an <code>sf</code> object; <code>st_transform</code> converts the data from one coordinate system to another.</li>
</ul>
<hr />
</div>
</div>
<div id="geomsf" class="section level2">
<h2>Customize maps with ggplot2</h2>
<p>While the <code>plot</code> function is useful to get an overview of a spatial dataset, other packages provide more customization options to create publication-quality maps. In this section, we will see how a widely-used R graphics package, <strong><em>ggplot2</em></strong>, also supports mapping of spatial datasets.</p>
<p>For those not familiar with <strong><em>ggplot2</em></strong>, a comprehensive introduction can be found in the <a href="https://r4ds.had.co.nz/data-visualisation.html">Data Visualisation</a> chapter of <em>R for Data Science</em> by Wickham and Grolemund. Producing any type of graph with <strong><em>ggplot2</em></strong> requires a similar sequence of steps:</p>
<ul>
<li>Specify the dataset as well as aesthetic mappings (<code>aes</code>), which associate variables in the data to graphical elements (<em>x</em> and <em>y</em> axes, color or size scale, etc.);</li>
<li>Add <code>geom_</code> layers, which specify the type of graph;</li>
<li>Optionally, specify additional customization options such as axis names and limits, color themes, and more.</li>
</ul>
<p>For example, the following code creates a bar plot (<code>geom_bar</code>) from the forest inventory plots data (<code>data = plots</code>), showing the number of forest plots by height class (<em>x</em> axis) and by cover type (different fill colors of the bars). The <code>labs</code> function defines custom labels for the title, axes and legend.</p>
<pre class="r"><code>library(ggplot2)

ggplot(data = plots, aes(x = height_cls, fill = cover_type)) + 
    geom_bar() +
    labs(title = &quot;Forest inventory plots&quot;, x = &quot;Height class&quot;, 
         y = &quot;Count&quot;, fill = &quot;Cover type&quot;)</code></pre>
<p><img src="rgeo_workshop_files/figure-html/ggplot_bar-1.png" width="672" /></p>
<p>When plotting a vector dataset from an <code>sf</code> object, we use the <code>geom_sf</code> layer to display the spatial features on a map. It is not necessary to specify <em>x</em> and <em>y</em> mappings in <code>aes</code>, since these are defined by the <code>sf</code> object itself. The graticule lines are also automatically drawn.</p>
<pre class="r"><code>ggplot(data = mrc_proj) +
    geom_sf()</code></pre>
<p><img src="rgeo_workshop_files/figure-html/geom_sf-1.png" width="672" /></p>
<p>To add multiple spatial layers to the same map, we simply add more <code>geom_sf</code> layers, which can be based on different datasets (specifying the <code>data</code> argument in each <code>geom</code>). In the code below, we add a point layer for the forest inventory plots, assigning the color aesthetic to cover type. We also use <code>theme_set(theme_bw())</code> to change from the default grey theme to the black and white theme in all future plots.</p>
<pre class="r"><code>theme_set(theme_bw())
ggplot() +
    geom_sf(data = mrc_proj) +
    geom_sf(data = plots, aes(color = cover_type), size = 1)</code></pre>
<p><img src="rgeo_workshop_files/figure-html/geom_sf_mult-1.png" width="672" /></p>
<p>When a graphical element is set to a constant outside of the <code>aes</code> function, it is applied to the whole layer; therefore <code>size = 1</code> means that all points will be of size 1.</p>
<p>Notice that the two spatial datasets plotted above use different CRS:</p>
<pre class="r"><code>st_crs(mrc_proj)</code></pre>
<pre><code>## Coordinate Reference System:
##   User input: EPSG:6622 
##   wkt:
## PROJCS[&quot;NAD83(CSRS) / Quebec Lambert&quot;,
##     GEOGCS[&quot;NAD83(CSRS)&quot;,
##         DATUM[&quot;NAD83_Canadian_Spatial_Reference_System&quot;,
##             SPHEROID[&quot;GRS 1980&quot;,6378137,298.257222101,
##                 AUTHORITY[&quot;EPSG&quot;,&quot;7019&quot;]],
##             TOWGS84[0,0,0,0,0,0,0],
##             AUTHORITY[&quot;EPSG&quot;,&quot;6140&quot;]],
##         PRIMEM[&quot;Greenwich&quot;,0,
##             AUTHORITY[&quot;EPSG&quot;,&quot;8901&quot;]],
##         UNIT[&quot;degree&quot;,0.0174532925199433,
##             AUTHORITY[&quot;EPSG&quot;,&quot;9122&quot;]],
##         AUTHORITY[&quot;EPSG&quot;,&quot;4617&quot;]],
##     PROJECTION[&quot;Lambert_Conformal_Conic_2SP&quot;],
##     PARAMETER[&quot;standard_parallel_1&quot;,60],
##     PARAMETER[&quot;standard_parallel_2&quot;,46],
##     PARAMETER[&quot;latitude_of_origin&quot;,44],
##     PARAMETER[&quot;central_meridian&quot;,-68.5],
##     PARAMETER[&quot;false_easting&quot;,0],
##     PARAMETER[&quot;false_northing&quot;,0],
##     UNIT[&quot;metre&quot;,1,
##         AUTHORITY[&quot;EPSG&quot;,&quot;9001&quot;]],
##     AXIS[&quot;X&quot;,EAST],
##     AXIS[&quot;Y&quot;,NORTH],
##     AUTHORITY[&quot;EPSG&quot;,&quot;6622&quot;]]</code></pre>
<pre class="r"><code>st_crs(plots)</code></pre>
<pre><code>## Coordinate Reference System:
##   User input: 4269 
##   wkt:
## GEOGCS[&quot;GCS_North_American_1983&quot;,
##     DATUM[&quot;North_American_Datum_1983&quot;,
##         SPHEROID[&quot;GRS_1980&quot;,6378137,298.257222101]],
##     PRIMEM[&quot;Greenwich&quot;,0],
##     UNIT[&quot;Degree&quot;,0.017453292519943295],
##     AUTHORITY[&quot;EPSG&quot;,&quot;4269&quot;]]</code></pre>
<p>In this case, <strong><em>ggplot2</em></strong> automatically transforms all layers to the same CRS before plotting; by default, it is the CRS of the first dataset, but a different CRS can be specified with the <code>coord_sf</code> function.</p>
<pre class="r"><code>ggplot(data = plots) +
    geom_sf() +
    coord_sf(crs = 6622)</code></pre>
<p><img src="rgeo_workshop_files/figure-html/ggplot_crs-1.png" width="672" /></p>
<p>In addition, <code>coord_sf</code> can be used to set coordinate axis limits and zoom in a portion of the map.</p>
<pre class="r"><code>ggplot(data = regions) +
    geom_sf(aes(fill = pop2016)) +
    geom_sf_label(aes(label = reg_name)) +
    coord_sf(xlim = c(-75, -70), ylim = c(45, 47))</code></pre>
<pre><code>## Warning in st_point_on_surface.sfc(sf::st_zm(x)): st_point_on_surface may not
## give correct results for longitude/latitude data</code></pre>
<p><img src="rgeo_workshop_files/figure-html/coord_sf-1.png" width="672" /></p>
<p>This last example introduced a new geom <code>geom_sf_label</code>, which adds a text label to each feature based on a value defined by the <code>label</code> aesthetic. The geom <code>geom_sf_text</code> works the same way, but does not draw a white box around the text label.</p>
<div id="retour2" class="section level3">
<h3>Exercise 2</h3>
<p>Create a map of the MRCs with different fill colors for each region.</p>
<p><a href="#sol2">Solution</a></p>
</div>
<div id="review-2" class="section level3">
<h3>Review</h3>
<ul>
<li>A <strong><em>ggplot2</em></strong> graph starts with a call to the <code>ggplot()</code> function, followed by specific <code>geom</code> defining each graph layer, followed by optional customization functions.</li>
<li>The <code>data</code> argument specifies the dataset to plot and the <code>aes</code> function associates variables in that dataset to graphical elements. These can be defined in the <code>ggplot</code> function (if they apply to all layers) or in specific <code>geom</code> layers.</li>
<li>The <code>geom_sf</code> layer plots an <code>sf</code> object on a map.</li>
<li>The <code>geom_sf_text</code> or <code>geom_sf_label</code> layers can be used to add textual data to each spatial feature on a map.</li>
<li>The <code>coord_sf</code> function defines axis limits and the CRS to use, transforming all spatial features to that CRS. By default, the CRS of the first plotted spatial dataset is used.</li>
</ul>
</div>
<div id="other-mapping-packages" class="section level3">
<h3>Other mapping packages</h3>
<p>The <strong><em>tmap</em></strong> package (see <a href="https://cran.r-project.org/web/packages/tmap/vignettes/tmap-getstarted.html">this tutorial</a>) is another option for producing maps in R. It was developed before <strong><em>ggplot2</em></strong> supported <code>sf</code> objects and functions with a similar layering logic.</p>
<hr />
</div>
</div>
<div id="vectop" class="section level2">
<h2>Geometric operations on vector data</h2>
<p>The <strong><em>sf</em></strong> package includes a number of geometric operations for vector data, which are similar to those found in geodatabases or GIS software. These operations can be grouped into three classes:</p>
<ul>
<li>predicates, or tests which output TRUE or FALSE (e.g. is geometry A inside B?);</li>
<li>measures, which produce a scalar quantity (e.g. length of a line, area of a polygon, distance between two geometries);</li>
<li>geometry-generating functions which produce output geometries based on input (e.g. distance buffer around a point, centroid of a polygon, intersection of two lines or polygons).</li>
</ul>
<p>In this workshop, we will present a few examples of each class. For a more detailed presentation, see Chapter 5 of the <em>Spatial Data Science</em> book listed in the <a href="#ref">additional references</a>.</p>
<p>First, we use <code>st_area</code> to calculate the area of each MRC in the original dataset.</p>
<pre class="r"><code>areas &lt;- st_area(mrc)
head(areas)</code></pre>
<pre><code>## Units: [m^2]
## [1]   7940855145   3630423258    582240572 513075556996  16304017180
## [6]   1335860444</code></pre>
<p>Note that the answer is in square metres, even though <code>mrc</code> uses geographical coordinates. Three measure functions: <code>st_area</code>, <code>st_length</code> and <code>st_distance</code> implement geodetic measures which take into account the curvature of the Earth. This is not the case for other operations, as we will see below.</p>
<p>To make it easier to read the results, we can convert them to a different unit.</p>
<pre class="r"><code>units(areas) &lt;- &quot;km^2&quot;
head(areas)</code></pre>
<pre><code>## Units: [km^2]
## [1]   7940.8551   3630.4233    582.2406 513075.5570  16304.0172   1335.8604</code></pre>
<p>As an example of a spatial predicate, let us now find where the points in <code>plots</code> and the polygons in <code>mrc</code> <em>intersect</em>, i.e. which individual features have points in common.</p>
<pre class="r"><code>inters &lt;- st_intersects(plots, mrc)</code></pre>
<pre><code>## although coordinates are longitude/latitude, st_intersects assumes that they are planar
## although coordinates are longitude/latitude, st_intersects assumes that they are planar</code></pre>
<pre class="r"><code>inters[1:3] # look at the first 3 elements in the output</code></pre>
<pre><code>## [[1]]
## [1] 94
## 
## [[2]]
## [1] 94
## 
## [[3]]
## [1] 53</code></pre>
<p>When comparing two spatial objects with a predicate like <code>st_intersects</code>, the result is a list of the same length as the first object (here, <code>plots</code>). Each element of that list contains the indices of the features in the second object for which the predicate is true. In this example, the first list element (<code>[[1]]</code>) indicates that plot 1 intersects with MRC 94, the third element indicates that plot 3 intersects with MRC 53, etc. Here each plot intersects with a single MRC, but in general an element of the intersection could be empty (if that feature in the first object has no intersection with the second object) or contain many indices (if that feature overlaps with multiple ones in object 2).</p>
<p>The warning text:</p>
<p>“although coordinates are longitude/latitude, st_intersects assumes that they are planar”,</p>
<p>indicates that this function treats geographical coordinates as if they were X-Y coordinates on a plane. In particular, the boundaries of a polygon are not the shortest lines between its vertices, since they ignore the curvature of the Earth. The difference is usually minor unless the line segments are very long, if they are near a pole or the international date line (where longitude jumps from -180 to 180 degrees).</p>
<p>From the results of <code>st_intersects</code> above, we could look up the indices to find the name of the MRC in which each inventory plot is located. Fortunately, there is a spatial join function <code>st_join</code> that automates this process, by appending to one <code>sf</code> object the data fields from a second <code>sf</code> object where the features intersect.</p>
<pre class="r"><code>plots_mrc &lt;- st_join(plots, mrc)</code></pre>
<pre><code>## although coordinates are longitude/latitude, st_intersects assumes that they are planar
## although coordinates are longitude/latitude, st_intersects assumes that they are planar</code></pre>
<pre class="r"><code>head(plots_mrc)</code></pre>
<pre><code>## Simple feature collection with 6 features and 8 fields
## Geometry type: POINT
## Dimension:     XY
## Bounding box:  xmin: -72.8958 ymin: 45.35944 xmax: -71.1618 ymax: 45.49196
## CRS:           4269
##    plot_id  surv_date cover_type height_cls               mrc_name reg_id
## 1 99100101 2012-11-12  Deciduous    17-22 m               Rouville     16
## 2 99100102 2012-09-08  Deciduous      &gt;22 m               Rouville     16
## 3 99100201 2008-09-11  Deciduous    17-22 m Le Haut-Saint-Francois     05
## 4 99100202 2008-09-11  Deciduous    17-22 m Le Haut-Saint-Francois     05
## 5 99100301 2012-08-30  Deciduous      &gt;22 m       La Haute-Yamaska     16
## 6 99100302 2012-08-30  Deciduous      &gt;22 m       La Haute-Yamaska     16
##     reg_name pop2016                   geometry
## 1 Monteregie   36724  POINT (-72.8958 45.35944)
## 2 Monteregie   36724 POINT (-72.89244 45.36267)
## 3     Estrie   22376 POINT (-71.16727 45.49196)
## 4     Estrie   22376  POINT (-71.1618 45.49068)
## 5 Monteregie   88683 POINT (-72.58792 45.47711)
## 6 Monteregie   88683 POINT (-72.58448 45.47969)</code></pre>
<p>By default, <code>st_join</code> performs a “left” join, meaning that it keeps all rows in the first dataset, and adds <em>NA</em> values to the extra fields when there is no match in the second dataset. We can see this by joining the <code>plots</code> data with the subset of MRC for regions 01 and 11 (see Exercise 1).</p>
<pre class="r"><code>mrc_01_11 &lt;- mrc[mrc$reg_id %in% c(&quot;01&quot;, &quot;11&quot;), ]
plots_01_11 &lt;- st_join(plots, mrc_01_11)</code></pre>
<pre><code>## although coordinates are longitude/latitude, st_intersects assumes that they are planar
## although coordinates are longitude/latitude, st_intersects assumes that they are planar</code></pre>
<pre class="r"><code>head(plots_01_11)</code></pre>
<pre><code>## Simple feature collection with 6 features and 8 fields
## Geometry type: POINT
## Dimension:     XY
## Bounding box:  xmin: -72.8958 ymin: 45.35944 xmax: -71.1618 ymax: 45.49196
## CRS:           4269
##    plot_id  surv_date cover_type height_cls mrc_name reg_id reg_name pop2016
## 1 99100101 2012-11-12  Deciduous    17-22 m     &lt;NA&gt;   &lt;NA&gt;     &lt;NA&gt;      NA
## 2 99100102 2012-09-08  Deciduous      &gt;22 m     &lt;NA&gt;   &lt;NA&gt;     &lt;NA&gt;      NA
## 3 99100201 2008-09-11  Deciduous    17-22 m     &lt;NA&gt;   &lt;NA&gt;     &lt;NA&gt;      NA
## 4 99100202 2008-09-11  Deciduous    17-22 m     &lt;NA&gt;   &lt;NA&gt;     &lt;NA&gt;      NA
## 5 99100301 2012-08-30  Deciduous      &gt;22 m     &lt;NA&gt;   &lt;NA&gt;     &lt;NA&gt;      NA
## 6 99100302 2012-08-30  Deciduous      &gt;22 m     &lt;NA&gt;   &lt;NA&gt;     &lt;NA&gt;      NA
##                     geometry
## 1  POINT (-72.8958 45.35944)
## 2 POINT (-72.89244 45.36267)
## 3 POINT (-71.16727 45.49196)
## 4  POINT (-71.1618 45.49068)
## 5 POINT (-72.58792 45.47711)
## 6 POINT (-72.58448 45.47969)</code></pre>
<p>With the optional argument <code>left = FALSE</code>, we can keep only the plots located in the two target regions.</p>
<pre class="r"><code>mrc_01_11 &lt;- mrc[mrc$reg_id %in% c(&quot;01&quot;, &quot;11&quot;), ]
plots_01_11 &lt;- st_join(plots, mrc_01_11, left = FALSE)</code></pre>
<pre><code>## although coordinates are longitude/latitude, st_intersects assumes that they are planar
## although coordinates are longitude/latitude, st_intersects assumes that they are planar</code></pre>
<pre class="r"><code>ggplot() +
    geom_sf(data = mrc_01_11) +
    geom_sf(data = plots_01_11)</code></pre>
<p><img src="rgeo_workshop_files/figure-html/st_join_inner-1.png" width="672" /></p>
<div id="retour3" class="section level3">
<h3>Exercise 3</h3>
<p>The shapefile <em>data/tbe2016_gaspe.shp</em> contains a map of areas defoliated by the spruce budworm in the Bas-St-Laurent and Gaspesie regions in 2016. The defoliation level is represented by an integer: 1 = Light, 2 = Moderate and 3 = Severe.</p>
<ol style="list-style-type: lower-alpha">
<li><p>How many forest inventory plots in these regions are affected at each defoliation level? <em>Hint</em>: The <code>table</code> function could be useful to get counts of each value in a column.</p></li>
<li><p>Plot the defoliated areas located in the MRC of Kamouraska, along with the MRC border.</p></li>
</ol>
<p><a href="#sol3">Solution</a></p>
<p>Finally, we consider a few geometry-generating functions. The <code>st_buffer</code> function creates a buffer at a set distance from each geometry in an object. For example, we can define a 5 km radius around each point in <code>plots_01_11</code>. This function does not work with geographical coordinates (longitude and latitude), so we first project the plots in EPSG 6622. The buffer distance is set in the units of the CRS, in this case metres.</p>
<pre class="r"><code>plots_proj &lt;- st_transform(plots_01_11, crs = 6622)
plots_buffer &lt;- st_buffer(plots_proj, dist = 5000)

ggplot() +
    geom_sf(data = plots_buffer, linetype = &quot;dotted&quot;, fill = NA) +
    geom_sf(data = plots_proj)</code></pre>
<p><img src="rgeo_workshop_files/figure-html/st_buffer-1.png" width="672" /></p>
<p>If the original feature is a polygon, a negative buffer distance creates a buffer inside the polygon.</p>
<pre class="r"><code>mrc_01_11_proj &lt;- st_transform(mrc_01_11, crs = 6622)
mrc_buffer &lt;- st_buffer(mrc_01_11_proj, dist = -5000)

ggplot() +
    geom_sf(data = mrc_buffer, linetype = &quot;dotted&quot;, fill = NA) +
    geom_sf(data = mrc_01_11_proj, fill = NA)</code></pre>
<p><img src="rgeo_workshop_files/figure-html/st_buffer_neg-1.png" width="672" /></p>
<p>Next, we will see three functions based on set operations. If <em>A</em> and <em>B</em> are geometric features, their union is the area covered by A or B, their intersection is the area covered by both A and B, and the difference (A - B) is the area covered by A, but not B. In <code>sf</code>, these operations are implemented by <code>st_union</code>, <code>st_intersection</code> and <code>st_difference</code>.</p>
<p>If they are applied to two <code>sf</code> objects (each of them containing multiple features in a column), then the function calculates the union, intersection or difference between all possible pairs of one feature from A and one feature from B. When applied to a single <code>sf</code> object, the <code>st_union</code> function merges all features in that object.</p>
<p>In the following example, <code>buffer_union</code> is a single geometric object, a multipolygon that covers all areas included in the individual buffers. The variables, or attributes, associated with individual features are lost in the merge.</p>
<pre class="r"><code>buffer_union &lt;- st_union(mrc_buffer)

ggplot(buffer_union) +
    geom_sf()</code></pre>
<p><img src="rgeo_workshop_files/figure-html/buffer_union-1.png" width="672" /></p>
<p>We then use <code>st_difference</code> to extract the 5km “edges” of the MRC polygons that are outside the combined buffer.</p>
<pre class="r"><code>mrc_edge &lt;- st_difference(mrc_01_11_proj, buffer_union)</code></pre>
<pre><code>## Warning: attribute variables are assumed to be spatially constant throughout all
## geometries</code></pre>
<pre class="r"><code>ggplot(mrc_edge) +
    geom_sf()</code></pre>
<p><img src="rgeo_workshop_files/figure-html/st_diff-1.png" width="672" /></p>
<p>Note that <code>st_difference</code> copies the data fields from the original datasets (here, only from <code>mrc_01_11_proj</code>, since <code>buffer_union</code> has no associated data). The warning (“attribute variables are assumed to be spatially constant”) reminds us that those variables might not match the new geometries. For example, the <em>pop2016</em> variable in <code>mrc_edge</code> refers to the original MRC, not the portion extracted by <code>st_difference</code>.</p>
</div>
<div id="review-3" class="section level3">
<h3>Review</h3>
<ul>
<li>The <strong><em>sf</em></strong> package includes <em>measure</em> functions for the area of polygons (<code>st_area</code>), the length of a line (<code>st_length</code>) or the distance between pairs of geometric features (<code>st_distance</code>). Those functions work with either geographic (long, lat) or projected coordinate systems.</li>
<li>All other geometric operations in <strong><em>sf</em></strong> are based on planar geometry. They treat longitude and latitude as if they were perpendicular axes (<em>x</em>, <em>y</em>).</li>
<li><code>st_intersects(A, B)</code> is an example of a spatial <em>predicate</em>: for each element in <em>A</em>, the function returns the indices of elements with <em>B</em> that intersect with it.</li>
<li><code>st_join(A, B)</code> takes an <code>sf</code> object <em>A</em> and appends the data fields from a second object <em>B</em> for each case where the feature in <em>A</em> intersects with a feature in <em>B</em>. Contrary to <code>st_intersection</code> below, the geometric features themselves do not change; the result retains the features from <em>A</em>.</li>
<li><code>st_intersection(A, B)</code> produces a dataset containing all regions where features in <em>A</em> and <em>B</em> overlap.</li>
<li><code>st_difference(A, B)</code> produces a dataset containing the set differences (portion of <em>A</em> not in <em>B</em>) for each pair of features in <em>A</em> and <em>B</em>.</li>
<li><code>st_union(A, B)</code> produces a dataset containing the unions (area covered by either <em>A</em> or <em>B</em>) for each pair of features in <em>A</em> and <em>B</em>. When given a single <code>sf</code> object as input, <code>st_union</code> merges all features from that object within a single one.</li>
<li><code>st_buffer</code> produces new geometric features that buffer the input features by a given distance.</li>
</ul>
<hr />
</div>
</div>
<div id="rast" class="section level2">
<h2>Raster datasets</h2>
<p>The <em>data</em> folder contains a raster file covering sections 022B and 022C from the <a href="https://ouvert.canada.ca/data/fr/dataset/7f245e4d-76c2-4caa-951a-45d1d2051333">Canadian Digital Elevation Model</a> or CDEM.</p>
<p>The CDEM is a raster dataset; the area of Canada is covered by a regular grid and the model associates an elevation value (in metres) to each pixel on that grid. This type of data is analogous to a digital image (rectangular array of pixels), to which metadata is added (resolution, spatial extent and coordinate system) so that each pixel can be associated to geographical coordinates.</p>
<p>The base resolution of the CDEM is 1/4800th of a degree and data are available in sections of 2 degrees of longitude by 1 degree of latitude. The data file we use in this workshop contains two sections (4 degrees of longitude by 1 degree of latitude), but was aggregated to a lower resolution (1/1200th of a degree, or 3 arc-seconds) to reduce processing time.</p>
<p>We first load the CDEM file, which is in the GeoTIFF raster format, with the <code>read_stars</code> function of the <strong><em>stars</em></strong> package (the name is an acronym for <strong>s</strong>patio<strong>t</strong>emporal <strong>ar</strong>ray<strong>s</strong>). This function associates the dataset to a <code>stars</code> object. Typing the object’s name at the command line shows a summary of the data and metadata.</p>
<pre class="r"><code>library(stars)
cdem &lt;- read_stars(&quot;data/cdem_022BC_3s.tif&quot;)
cdem</code></pre>
<pre><code>## stars object with 2 dimensions and 1 attribute
## attribute(s), summary of first 1e+05 cells:
##  cdem_022BC_3s.tif 
##  Min.   :   2.0    
##  1st Qu.:   2.0    
##  Median : 129.1    
##  Mean   : 189.8    
##  3rd Qu.: 328.8    
##  Max.   :1179.4    
## dimension(s):
##   from   to   offset        delta                       refsys point values x/y
## x    1 4801 -70.0001  0.000833333 GEOGCS[&quot;NAD83&quot;,DATUM[&quot;Nor... FALSE   NULL [x]
## y    1 1201  49.0001 -0.000833333 GEOGCS[&quot;NAD83&quot;,DATUM[&quot;Nor... FALSE   NULL [y]</code></pre>
<p>The CDEM data has one <em>attribute</em> (variable), the elevation, which ranges from 2 to 1179 m for this particular section. The <em>dimensions</em> table includes a row for each array dimension, here <em>x</em> and <em>y</em>. The <em>from</em> and <em>to</em> columns indicate the range of indices in each dimension (4801 cells in <em>x</em> by 1201 cells in <em>y</em>), the <em>offset</em> column contains the coordinates of the top-left corner of the raster (70 degrees West, 49 degrees North), the <em>delta</em> column indicates the size of each raster cell (1/1200 <span class="math inline">\(\approx\)</span> 0.000833 degree), and the <em>refsys</em> column describes the coordinate reference system.</p>
<p><em>Notes</em></p>
<ul>
<li><p>The negative <em>delta</em> for <em>y</em> means that latitude decreases from the top (north) to the bottom (south) of the raster.</p></li>
<li><p>While we limit ourselves to two-dimensional rasters in this workshop, one advantage of the <strong><em>stars</em></strong> package is that it easily incorporates additional dimensions beyond the two spatial dimensions, such as time or spectral band, which are common in remote sensing data.</p></li>
</ul>
<p>We can also determine the extent and coordinate system of the object with the same methods we used for <code>sf</code> objects.</p>
<pre class="r"><code>st_bbox(cdem)</code></pre>
<pre><code>##      xmin      ymin      xmax      ymax 
## -70.00010  47.99927 -65.99927  49.00010</code></pre>
<pre class="r"><code>st_crs(cdem)</code></pre>
<pre><code>## Coordinate Reference System:
##   User input: GEOGCS[&quot;NAD83&quot;,DATUM[&quot;North_American_Datum_1983&quot;,SPHEROID[&quot;GRS 1980&quot;,6378137,298.2572221010042,AUTHORITY[&quot;EPSG&quot;,&quot;7019&quot;]],TOWGS84[0,0,0,0,0,0,0],AUTHORITY[&quot;EPSG&quot;,&quot;6269&quot;]],PRIMEM[&quot;Greenwich&quot;,0],UNIT[&quot;degree&quot;,0.0174532925199433],AUTHORITY[&quot;EPSG&quot;,&quot;4269&quot;]] 
##   wkt:
## GEOGCS[&quot;NAD83&quot;,
##     DATUM[&quot;North_American_Datum_1983&quot;,
##         SPHEROID[&quot;GRS 1980&quot;,6378137,298.2572221010042,
##             AUTHORITY[&quot;EPSG&quot;,&quot;7019&quot;]],
##         TOWGS84[0,0,0,0,0,0,0],
##         AUTHORITY[&quot;EPSG&quot;,&quot;6269&quot;]],
##     PRIMEM[&quot;Greenwich&quot;,0],
##     UNIT[&quot;degree&quot;,0.0174532925199433],
##     AUTHORITY[&quot;EPSG&quot;,&quot;4269&quot;]]</code></pre>
<p>We can extract the elevation values as a regular R array with <code>cdem[[1]]</code>, which pulls the first (in this case the only) variable in the raster file. However, this removes the associated metadata.</p>
<pre class="r"><code>elev &lt;- cdem[[1]]
str(elev)</code></pre>
<pre><code>##  num [1:4801, 1:1201] 599 607 610 612 612 ...</code></pre>
<div id="plot-a-raster" class="section level3">
<h3>Plot a raster</h3>
<p>The <code>plot</code> function creates a quick 2D image (or heat map) of the raster data.</p>
<pre class="r"><code>plot(cdem)</code></pre>
<p><img src="rgeo_workshop_files/figure-html/plot_stars-1.png" width="672" /></p>
<p>We can also display a <code>stars</code> object in <strong><em>ggplot2</em></strong> with the <code>geom_stars</code> function. Because rasters can contain many more pixels than are visible at once on the screen, it is useful to apply a downsampling factor to speed up plotting. Here, <code>downsample = 5</code> means that 1 of every 5 pixels is shown.</p>
<pre class="r"><code>ggplot() +
    geom_stars(data = cdem, downsample = 5) +
    geom_sf(data = mrc_01_11, color = &quot;white&quot;, fill = NA) +
    scale_fill_viridis_c() +
    coord_sf(xlim = c(-70, -66), ylim = c(48, 49))</code></pre>
<p><img src="rgeo_workshop_files/figure-html/geom_stars-1.png" width="672" /></p>
<p>The <code>plot</code> function above automatically downsampled the data according to the screen’s resolution.</p>
</div>
<div id="work-with-large-raster-files" class="section level3">
<h3>Work with large raster files</h3>
<p>For raster files that are too large to load in memory, you can use the <code>proxy = TRUE</code> argument in <code>read_stars</code>. In that case, R loads a <code>stars_proxy</code> object containing the metadata, but not the pixel values. All raster operations can be applied to <code>stars_proxy</code> objects as well, but the calculations are not actually performed until the result is plotted (in which case only a fraction of pixels are processed due to downsampling) or the object is saved to disk (with <code>write_stars</code>).</p>
</div>
<div id="raster-operations" class="section level3">
<h3>Raster operations</h3>
<p>To crop a rectangular section of the raster, we can use the <code>filter</code> function from <strong><em>dplyr</em></strong> along one or multiple dimensions. For example, here is the portion of the raster east of 67 degrees West.</p>
<pre class="r"><code>cdem_part &lt;- filter(cdem, x &gt; -67)
plot(cdem_part)</code></pre>
<p><img src="rgeo_workshop_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>To crop a raster’s extent along the boundaries of a <code>sf</code> object, we use the <code>st_crop</code> function. The following code shows the elevation of points in the MRC of La Mitis. Note that we converted the polygon to the CRS of the raster prior to cropping.</p>
<pre class="r"><code>mitis &lt;- filter(mrc_01_11, mrc_name == &quot;La Mitis&quot;)
mitis &lt;- st_transform(mitis, st_crs(cdem))
cdem_mitis &lt;- st_crop(cdem, mitis)</code></pre>
<pre><code>## although coordinates are longitude/latitude, st_union assumes that they are planar</code></pre>
<pre><code>## although coordinates are longitude/latitude, st_intersects assumes that they are planar</code></pre>
<pre class="r"><code>plot(cdem_mitis)</code></pre>
<p><img src="rgeo_workshop_files/figure-html/st_crop-1.png" width="672" /></p>
<p>Since <code>stars</code> objects are fundamentally arrays of values, we can apply mathematical operations to each pixel just like we would for a regular array in R.</p>
<pre class="r"><code># Convert elevation values to km
cdem_km &lt;- cdem / 1000
plot(cdem_km)</code></pre>
<p><img src="rgeo_workshop_files/figure-html/raster_math-1.png" width="672" /></p>
<pre class="r"><code># Display points above 500 m in elevation
cdem_500 &lt;- cdem &gt; 500
plot(cdem_500)</code></pre>
<p><img src="rgeo_workshop_files/figure-html/raster_math-2.png" width="672" /></p>
</div>
<div id="retour4" class="section level3">
<h3>Exercise 4</h3>
<ol style="list-style-type: lower-alpha">
<li><p>Show on a map where the elevation is between 5 and 100 m in the MRC of La Mitis.</p></li>
<li><p>What is the highest elevation in that MRC?</p></li>
</ol>
<p><a href="#sol4">Solution</a></p>
</div>
<div id="extract-values-from-raster-at-points" class="section level3">
<h3>Extract values from raster at points</h3>
<p>A common use of raster data is to extract values at points of interest. For example, we might want elevation values for each of the forest inventory plots in <code>plots_01_11</code>.</p>
<p>Since the <strong><em>stars</em></strong> package does not have a fast option for point extraction, we will use the <strong><em>raster</em></strong> package and its <code>extract</code> function.</p>
<pre class="r"><code>library(raster)
cdem_r &lt;- as(cdem, &quot;Raster&quot;) # convert from stars to raster format
plots_elev &lt;- extract(cdem_r, plots_01_11)

plots_01_11$elev &lt;- plots_elev # save in a new column of the sf object

head(plots_01_11)</code></pre>
<pre><code>## Simple feature collection with 6 features and 9 fields
## Geometry type: POINT
## Dimension:     XY
## Bounding box:  xmin: -67.02499 ymin: 48.36367 xmax: -64.41216 ymax: 48.52901
## CRS:           4269
##      plot_id  surv_date cover_type height_cls        mrc_name reg_id
## 17 119600101 2016-06-16 Coniferous    17-22 m     Bonaventure     11
## 18 119600102 2016-06-16 Coniferous    17-22 m     Bonaventure     11
## 19 119600201 2015-06-03 Coniferous    12-17 m    La Matapedia     01
## 20 119600202 2015-06-03 Coniferous    12-17 m    La Matapedia     01
## 21 119600301 2016-06-15 Coniferous    12-17 m Le Rocher-Perce     11
## 22 119600302 2016-06-14 Coniferous    12-17 m Le Rocher-Perce     11
##                           reg_name pop2016                   geometry     elev
## 17 Gaspesie - Iles-de-la-Madeleine   17664  POINT (-65.43818 48.3653)       NA
## 18 Gaspesie - Iles-de-la-Madeleine   17664 POINT (-65.43293 48.36367)       NA
## 19               Bas-Saint-Laurent   17935 POINT (-67.02499 48.36973) 453.1875
## 20               Bas-Saint-Laurent   17935 POINT (-67.02246 48.37316) 435.1875
## 21 Gaspesie - Iles-de-la-Madeleine   17311 POINT (-64.41546 48.52901)       NA
## 22 Gaspesie - Iles-de-la-Madeleine   17311  POINT (-64.41216 48.5262)       NA</code></pre>
</div>
<div id="review-4" class="section level3">
<h3>Review</h3>
<ul>
<li>A raster dataset associates a value to each pixel in a regular grid. The <strong><em>stars</em></strong> package allows us to process this type of data in R.</li>
<li>The <code>read_stars</code> function loads a raster file in R. For large files, specify <code>proxy = TRUE</code> to avoid loading the full raster in memory.</li>
<li>The <code>stars</code> object can be plotted by itself with <code>plot</code>, or added to a <code>ggplot</code> with <code>geom_stars</code>.</li>
<li><code>filter</code> crops a <code>stars</code> object along the specified dimensions, whereas <code>st_crop</code> crops it within the boundaries of an <code>sf</code> object.</li>
<li>Arithmetic (<code>+</code>, <code>-</code>, etc.) and comparison operators (<code>&lt;</code>, <code>==</code>, etc.) are applied to each pixel of the <code>stars</code> object.</li>
<li>The <code>extract</code> function from the <strong><em>raster</em></strong> package extracts raster values at specific points specified by an <code>sf</code> object.</li>
</ul>
<hr />
</div>
</div>
<div id="mapview" class="section level2">
<h2>Interactive maps with mapview</h2>
<p>The <strong><em>mapview</em></strong> package provides visualizations of <code>sf</code> and <code>raster</code> layers on an interactive map (similar to Google Maps) with different basemap options (e.g. OpenStreetMap, OpenTopoMap, ESRI World Imagery). We simply call the <code>mapview</code> function with the name of the spatial dataset. Multiple layers can be overlaid with the <code>+</code> operator.</p>
<p>There are a few optional arguments to control the plotting of each type of object. In the example below, we use the <code>zcol</code> argument to select the variable by which to color the points in <code>plots_01_11</code>.</p>
<pre class="r"><code>library(mapview)

mapview(cdem) +
    mapview(plots_01_11, zcol = &quot;cover_type&quot;)</code></pre>
<div class="figure">
<img src="images/mapview_example.png" alt="" />
<p class="caption">Exemple mapview</p>
</div>
<hr />
</div>
<div id="ref" class="section level2">
<h2>Additional references</h2>
<ul>
<li><p><a href="https://keen-swartz-3146c4.netlify.com/">Spatial Data Science</a>, a free online textbook by Edzer Pebesma and Roger Bivand that covers the <em>sf</em> and <em>stars</em> packages in more detail, in addition to subsequent chapters on statistical modelling of spatial data.</p></li>
<li><p><a href="https://geocompr.robinlovelace.net/">Geocomputation with R</a> (Lovelace, Nowosad and Muenchow) is another comprehensive free textbook for manipulating and analyzing spatial data.</p></li>
<li><p>The <a href="https://www.r-spatial.org">R-spatial blog</a> presents news and tutorials on spatial packages in R. In particular, see this series (<a href="https://www.r-spatial.org/r/2018/10/25/ggplot2-sf.html">1</a>, <a href="https://www.r-spatial.org/r/2018/10/25/ggplot2-sf-2.html">2</a>, <a href="https://www.r-spatial.org/r/2018/10/25/ggplot2-sf-3.html">3</a>) of posts by Mel Moreno and Mathieu Basille on mapping with <em>ggplot2</em>.</p></li>
<li><p>The <a href="https://rspatial.org/">RSpatial site</a> (not to be confused with the previous one) includes tutorials for the <em>raster</em> and <em>terra</em> packages to work with raster data.</p></li>
</ul>
<hr />
</div>
<div id="data" class="section level2">
<h2>Data sources</h2>
<p>This workshop uses public data made available by Québec and Canada government agencies. The script <code>data_prep.R</code> shows the detailed steps to produce the workshop data files from the original sources.</p>
<ul>
<li><p>County regional municipality (CRM) <a href="https://mern.gouv.qc.ca/territoire/portrait/portrait-donnees-mille.jsp">boundaries</a> were downloaded from the Québec Department of Energy and Natural Resources (MERN) and merged with <a href="https://www.stat.gouv.qc.ca/statistiques/population-demographie/structure/mrc-total.xlsx">population data</a> from the Institut de la statistique du Québec. Column names were translated to English and diacritic marks (accents) were removed from all place names.</p></li>
<li><p>Data on <a href="https://www.donneesquebec.ca/recherche/fr/dataset/placettes-echantillons-permanentes-1970-a-aujourd-hui">forest inventory plots</a> and <a href="https://www.donneesquebec.ca/recherche/fr/dataset/donnees-sur-les-perturbations-naturelles-insecte-tordeuse-des-bourgeons-de-lepinette">spruce budworm defoliation maps</a> from the Québec Department of Forests, Wildlife and Parks (MFFP) were downloaded from the Québec Open Data Portal. Some data fields were recoded and translated to English.</p></li>
<li><p><a href="https://open.canada.ca/data/en/dataset/7f245e4d-76c2-4caa-951a-45d1d2051333">Canadian Digital Elevation Model</a> rasters from Natural Resources Canada were downloaded from the Canada Open Data Portal. Two 2x1 degree sections were merged to use in this workshop.</p></li>
</ul>
<hr />
</div>
<div id="sol" class="section level2">
<h2>Solutions</h2>
<div id="sol1" class="section level3">
<h3>Exercise 1</h3>
<p>Select the MRCs in the Bas-St-Laurent (<em>reg_id</em>: 01) and Gaspesie (<em>reg_id</em>: 11) regions, then display their 2016 population on a map.</p>
<pre class="r"><code>mrc_01_11 &lt;- mrc[mrc$reg_id %in% c(&quot;01&quot;, &quot;11&quot;), ]
plot(mrc_01_11[&quot;pop2016&quot;], axes = TRUE)</code></pre>
<p><img src="rgeo_workshop_files/figure-html/sol1-1.png" width="672" /></p>
<p><a href="#retour1">Return to text</a></p>
</div>
<div id="sol2" class="section level3">
<h3>Exercise 2</h3>
<p>Create a map of the MRCs with different fill colors for each region.</p>
<pre class="r"><code>ggplot(data = mrc_proj, aes(fill = reg_name)) +
    geom_sf()</code></pre>
<p><img src="rgeo_workshop_files/figure-html/sol2-1.png" width="672" /></p>
<p><a href="#retour2">Return to text</a></p>
</div>
<div id="sol3" class="section level3">
<h3>Exercise 3</h3>
<ol style="list-style-type: lower-alpha">
<li>How many of the forest inventory plots in these regions are affected at each defoliation level?</li>
</ol>
<pre class="r"><code>defo &lt;- st_read(&quot;data/tbe2016_gaspe.shp&quot;)</code></pre>
<pre><code>## Reading layer `tbe2016_gaspe&#39; from data source `/research-home/rblake/atelier_rgeo/data/tbe2016_gaspe.shp&#39; using driver `ESRI Shapefile&#39;
## Simple feature collection with 3928 features and 2 fields
## Geometry type: POLYGON
## Dimension:     XY
## Bounding box:  xmin: -69.88925 ymin: 47.38829 xmax: -64.66188 ymax: 49.25522
## CRS:           4269</code></pre>
<pre class="r"><code>plots_defo &lt;- st_join(plots_01_11, defo)</code></pre>
<pre><code>## although coordinates are longitude/latitude, st_intersects assumes that they are planar
## although coordinates are longitude/latitude, st_intersects assumes that they are planar</code></pre>
<pre class="r"><code>table(plots_defo$level)</code></pre>
<pre><code>## 
##  1  2  3 
## 93 93 90</code></pre>
<ol start="2" style="list-style-type: lower-alpha">
<li>Plot the defoliated areas located in the MRC of Kamouraska by severity level, also displaying the MRC border.</li>
</ol>
<pre class="r"><code>mrc_kam &lt;- filter(mrc_01_11, mrc_name == &quot;Kamouraska&quot;)
defo_kam &lt;- st_join(defo, mrc_kam, left = FALSE)</code></pre>
<pre><code>## although coordinates are longitude/latitude, st_intersects assumes that they are planar</code></pre>
<pre class="r"><code>ggplot() +
    geom_sf(data = mrc_kam) +
    geom_sf(data = defo_kam, color = NA, aes(fill = level))</code></pre>
<p><img src="rgeo_workshop_files/figure-html/sol3b-1.png" width="672" /></p>
<p><a href="#retour3">Return to text</a></p>
</div>
<div id="sol4" class="section level3">
<h3>Exercise 4</h3>
<ol style="list-style-type: lower-alpha">
<li>Show on a map where the elevation is between 5 and 100 m in the MRC of La Mitis.</li>
</ol>
<pre class="r"><code>mitis &lt;- filter(mrc_01_11, mrc_name == &quot;La Mitis&quot;)
mitis &lt;- st_transform(mitis, st_crs(cdem))

cdem_mitis &lt;- st_crop(cdem, mitis)</code></pre>
<pre><code>## although coordinates are longitude/latitude, st_union assumes that they are planar</code></pre>
<pre><code>## although coordinates are longitude/latitude, st_intersects assumes that they are planar</code></pre>
<pre class="r"><code>plot(cdem_mitis &gt;= 5 &amp; cdem_mitis &lt;= 100)</code></pre>
<p><img src="rgeo_workshop_files/figure-html/sol4a-1.png" width="672" /></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>What is the highest elevation in that MRC?</li>
</ol>
<pre class="r"><code>cdem_mitis_vals &lt;- cdem_mitis[[1]]
max(cdem_mitis_vals, na.rm = TRUE)</code></pre>
<pre><code>## [1] 794.4375</code></pre>
<p><a href="#retour4">Return to text</a></p>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
